[project]
name = "20260218-auxine-calculation-md"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=7.2.0",
    "matplotlib>=3.10.8",
    "numpy<2.0.0",
    "opencv-python>=4.13.0.92",
    "pandas<2.2.0",
]
